---
- name: sync compiled dist to server
  synchronize:
    src: /root/project/backend/backend-dist.tgz
    dest: /home/ubuntu/backend

- name: "extract files"
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar xzvf backend-dist
    ls -la

- name: "Start App"
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start